### PR TITLE
[Admin] Use Rails.application.mounted_helpers in base component

### LINKED ISSUE #6038: Errors running in Production mode config.eager_load = true
**Solidus Version**:4.4.2

**To Reproduce**
Deployed to VPS via capistrano. Ruby 3.2.2 Rails 7.2.2.1
Navigate to admin/orders - error
NameError (undefined local variable or method `spree' for #<SolidusLegacyPromotions::Orders::Index::Component:0x00007f75d1a0b380

navigate to admin/products - error
NameError (undefined local variable or method `spree' for #<SolidusAdmin::Products::Index::Component:0x00007f75ca9ad7a0

With eager loading off pages load.

### PR DESCRIPTION
**Pull request by mamhoff**
Rather than implementing routing proxies ourselves, we can use what Rails offers.

Fixes #6038

### CODE REVIEW

File: admin/lib/solidus_admin/engine.rb [hunk 1]
```diff
@@ -63,5 +63,11 @@ class Engine < ::Rails::Engine
         SolidusAdmin::Engine.root.join("app/components"),
       ]
     end
+
+    initializer "solidus_admin.routing_proxies" do |app|
+      ActiveSupport.on_load(:after_routes_loaded) do
+        SolidusAdmin::BaseComponent.include app.routes.mounted_helpers
```
Comment (tvdeyen) [inline admin/lib/solidus_admin/engine.rb:69]: TIL `mounted_helpers` 🎉

**Review by tvdeyen — APPROVED** [review]

**Comment by kennyadsl** [comment]
I don't understand if failures are strictly related but it seems like it's the case.

**Comment by mamhoff** [comment]
Absolutely related. Will look into it tomorrow.

**Comment by mamhoff** [comment]
The failures were related, and fixed by the second commit in this PR.
