### PR TITLE
Raise on deprecation when `SOLIDUS_RAISE_DEPRECATIONS` set

### LINKED ISSUE #5766: Deprecation warnings don't raise when they should
When running the test suite while having `SOLIDUS_RAISE_DEPRECATIONS` set to `true`, we expect the test suite to fail if any code deprecated by `Spree.deprecator` is called. 

This is not the case currently; and I'm not sure how to fix it.

**Solidus Version**:
Current `main` (as of 2024-05-29)

**To Reproduce**

Deprecate a commonly called method, such as Spree::Order#recalculate by inserting
```
    deprecate :recalculate, deprecator: Spree.deprecator
```
into the core `order.rb` class.

Now run the following command: 

`SOLIDUS_RAISE_DEPRECATIONS=true rspec spec/models/spree/order_spec.rb:245` 

**Current behavior**
The spec calls `Spree::Order#recalculate`, which we just deprecated, and the test suite prints a warning.

**Expected behavior**
The spec calls `Spree::Order#recalculate`, which we just deprecated, and the test suite fails.

**Desktop (please complete the following information):**
 - OS: zsh on Fedora

**Additional context**

We can't currently be sure that we have no deprecation warnings in the test suite. I somewhat rely on this working because with the work on extracting legacy promotions, I work with a lot of deprecations and would like to be sure I don´t accidentally call deprecated code. 

My hunch is that this has to do with the move vom `Spree::Deprecation` to `Spree.deprecator`, which instacaches the instance on a module instance variable. It appears this instacaching doesn't work as it should.

### PR DESCRIPTION
**Pull request by forkata**
## Summary

Fixes #5766

This issue can be reproduced on the first commit by running the specs with the environment variable to override deprecation behaviour, as such

```
SOLIDUS_RAISE_DEPRECATIONS=true bundle exec rspec spec/lib/spree/deprecator_spec.rb
```

which produces the following output

```
Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Spree.deprecator by default does not raise an error unless overridden by environment
     # fix for deprecation behaviour override
     Failure/Error: expect { Dummy.new.deprecated_method }.to raise_error(ActiveSupport::DeprecationException)
       expected ActiveSupport::DeprecationException but nothing was raised
```

We were able to fix this issue by moving the code that sets the deprecation behaviour after the `DummyApp` is initialized, which seems to reset that.

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [x] I have written a thorough PR description.
- [x] I have kept my commits small and atomic.
- [x] [I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

The following are not always needed:

- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

### CODE REVIEW

**Review by tvdeyen — APPROVED** [review]
Nice work!

File: core/lib/spree/testing_support/dummy_app.rb [hunk 1]
```diff
@@ -41,6 +41,12 @@ def self.setup(gem_root:, lib_name:, auto_migrate: true)
     DummyApp::Application.config.root = root
     DummyApp::Application.initialize! unless DummyApp::Application.initialized?
 
+    # Raise on deprecation warnings.
+    # NOTE: This needs to happen after the appliaction is initilized.
```
Comment (benjaminwil) [inline core/lib/spree/testing_support/dummy_app.rb:45]: Just noticed a couple typos. Oops!

```suggestion
    # NOTE: This needs to happen after the application is initialized.

**Comment by benjaminwil** [comment]
It looks like this change has exposed some other tests that should have been raising exceptions but were not. (Because `SOLIDUS_RAISE_DEPRECATIONS` is set to `true` for CI runs.)

So we'll need to go back and fix those up before merging, it seems.

**Comment by kennyadsl** [comment]
Thanks for this! We should restore the previous behavior to spot failing specs for deprecations, like it's already happening it seems. Thanks again. ❤️

**Review by jarednorman — APPROVED** [review]

**Comment by benjaminwil** [comment]
Looks like we just need to rebase once #5814 is merged and all will be okay.

**Comment by kennyadsl** [comment]
We can rebase now, thanks!

File: core/lib/spree/testing_support/dummy_app.rb (hunk 1 above)
Comment (benjaminwil) [reply core/lib/spree/testing_support/dummy_app.rb]: Resolved.

**Review by MadelineCollier — APPROVED** [review]

**Review by kennyadsl — APPROVED** [review]
Thanks @forkata and @benjaminwil! ❤️
