### PR TITLE
Cast string values from params into boolean.

### LINKED ISSUE #1737: Stock Transfer receive dropdown autocomplete fails when all of stock in transit
I’m on the latest gem release of `2.0.x`. If I transfer all of the stock of a given product from one warehouse to another, I can’t "receive" the package correctly. The product is out of stock in all locations while it’s in transit, and when I go to log the received stock, the dropdown won’t show that product.

My workaround: go to Store Stock, manually change quantity at my receiving warehouse to 1, use the dropdown, change quantity manually back to 0, then receive the shipment.

### PR DESCRIPTION
**Pull request by gus4no**
This fixes #1737 

The issue was that the param was being set at `"false"` which is would add the `in_stock` scope to the variants because `"false" != false`.

So @jtapia and I ended up adding the query string param only if the condition was true.

### CODE REVIEW

**Comment by gmacdougall** [comment]
Could you help my understanding how you reproduced the issue? Taking a look at how this is initialized, I can only see it getting initialized with boolean values (example: https://github.com/solidusio/solidus/blob/v2.2.1/backend/app/assets/javascripts/spree/backend/stock_transfers/receive.coffee#L3) and not seeing where the string "false" came from.

**Comment by gus4no** [comment]
@gmacdougall About what we talked, what do you think of using this

`in_stock_only = ActiveRecord::Type::Boolean.new.cast(params[:in_stock_only])`

**Comment by gmacdougall** [comment]
I think that makes sense.

**Comment by gus4no** [comment]
@gmacdougall what do you think now?

**Comment by gmacdougall** [comment]
I think this is great. I might consider adding another spec for the specific case that you were having trouble with. For example, when `in_stock_only` is `"false"`

**Comment by gus4no** [comment]
@gmacdougall Tests added

**Comment by gus4no** [comment]
@tvdeyen Squashed! :)

File: api/spec/controllers/spree/api/variants_controller_spec.rb [hunk 1]
```diff
@@ -88,27 +88,56 @@ module Spree
...
+          subject { api_get :index, in_stock_only: "false" }
+
+          context "variant is out of stock" do
+            before do
+              variant.stock_items.update_all(count_on_hand: 0)
+            end
+
+            it "is not returned in the results" do
+              subject
+              expect(json_response["variants"].count).to eq 1
```
Comment (gmacdougall) [inline api/spec/controllers/spree/api/variants_controller_spec.rb]: This expectation doesn't seem to match the description here.

**Comment by gus4no** [comment]
@gmacdougall I think it's ready now!
