### PR TITLE
Apply store credits before creating payments

### LINKED ISSUE #3050: Store credits applied after the payment is created
**Describe the bug**

In the payment step, if the user has store credits, a first payment with the total amount is saved to the database. After that, store credits are subtracted from the payment and the amount is updated with the remaining total. This happens even if store credits completely cover the order total and the user still needs to input his credit card.

**Solidus Version**:

master

**To Reproduce**

1. Assign yourself some store credits in the admin area
2. Put a byebug [here](https://github.com/solidusio/solidus/blob/375305d7791c605d414f486792cffadee44778fd/core/app/models/spree/order.rb#L631)
3. Check how the payment evolves after each action
4. Complete the checkout

**Expected behavior**

The payment is directly saved with the correct amount on the database

**Additional context**

If this behavior is intended to be as it is now, I'm going to add some documentation to explain the reasons better.

### PR DESCRIPTION
**Pull request by ccarruitero**
This PR is sponsored by [MagmaLabs](https://www.magmalabs.io/)

## Summary

fix #3050 

Currently we are using the order total when set payment amount. This PR update to use total after store credit

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [X] I have written a thorough PR description.
- [X] I have kept my commits small and atomic.
- [X] I have used clear, explanatory commit messages.

The following are not always needed (~cross them out~ if they are not):

- [X] I have added automated tests to cover my changes.
- [ ] I have attached screenshots to demo visual changes.
- [ ] I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- [ ] I have updated the readme to account for my changes.

### CODE REVIEW

**Comment by kennyadsl** [comment]
Hey @ccarruitero! We'd like to move this PR forward. As always, it's taking a while and we are sorry for that. Can I please ask for a rebase. 

Thanks again for your contributions. 🙏

**Review by kennyadsl — APPROVED** [review]

**Review by waiting-for-dev — APPROVED** [review]

File: core/lib/spree/core/controller_helpers/payment_parameters.rb [hunk 1]
```diff
@@ -120,9 +120,7 @@ def move_wallet_payment_source_id_into_payments_attributes(params)
 
     # This is a strange thing to do since an order can have multiple payments
     # but we always assume that it only has a single payment and that its
-    # amount should be the current order total.  Also, this is pretty much
-    # overridden when the order transitions to confirm by the logic inside of
-    # Order#add_store_credit_payments.
+    # amount should be the current order totali after store credit is applied.
```
Comment (kennyadsl) [inline core/lib/spree/core/controller_helpers/payment_parameters.rb:123]:
```suggestion
    # amount should be the current order total after store credit is applied.
```

**Review by kennyadsl — COMMENTED** [review]
Found a small typo in the updated code comment.

File: core/lib/spree/core/controller_helpers/payment_parameters.rb (hunk 1 above)
Comment (ccarruitero) [reply core/lib/spree/core/controller_helpers/payment_parameters.rb:123]: Nice catch!

**Comment by kennyadsl** [comment]
Hey @ccarruitero, On your branch, the last commit is dated  `Oct 3, 2022`. I think you need to update the local base branch before rebasing. That's why specs are failing. 🙏
