### PR TITLE
Fixes to StockConfiguration

### LINKED ISSUE #725: Uninitialized constant Spree::StockConfiguration
Hello everyone,

Since commit ba839c005b9fa54b7944aefc9a257bc2daef8242, trying to access the current estimator creates a "Uninitialized constant Spree::StockConfiguration" exception.
Removing the leading double colons in this line seems to solve the bug:
https://github.com/solidusio/solidus/blob/eb761fb790d67732ac5fa59a4f6205ab749b5053/core/lib/spree/core/stock_configuration.rb#L4

### PR DESCRIPTION
**Pull request by jhawthorn**
Fixes the code reloading issue and also additional improvements.

This changes the class/module name which is used, which should be okay as 1.2 is the first release with  StockConfiguration.

Fixes #725

This will be backported to 1.2.0

### CODE REVIEW

File: core/app/models/spree/app_configuration.rb [hunk 1]
```diff
@@ -313,7 +312,7 @@ def static_model_preferences
     end
 
     def stock
-      Spree::StockConfiguration
+      @stock_configuration ||= Spree::StockConfiguration.new
```
Comment (tvdeyen) [inline core/app/models/spree/app_configuration.rb]: missing `Core`:

```ruby
@stock_configuration ||= Spree::Core::StockConfiguration.new
```

Comment (jhawthorn) [inline core/app/models/spree/app_configuration.rb]: Thanks

**Comment by cbrunsdon** [comment]
:+1: 

Thanks to @CallMeSH for working with me trying to reproduce this on slack. But of course @jhawthorn figured it out.
