### PR TITLE
Admin and User Metadata for transactional ressources and users (#5897)

### LINKED ISSUE #5897: MetaData support for Products, Orders and other resources
# Meta Data

### Overview 
I have broken meta data down in three large topics visible in the table below. 

|                         | Use Case                                                                                                                                                              |
|-------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Administrative Metadata | Information required to correlate all transactions to 3rd party systems.                                                                                              |
| Customer Metadata       | Information allowing customers to customize orders (eg options to store information like a text string or link to an image) or correlate transactions (such as POs).  |
| Public Metadata         | Add data to make the catalogue comply with either legal requirements (for example chemical composition, security warnings,...), operational requirements (such as GTIN,...) .                                                                                |

### Administrative Metadata
We do not believe that solidus is used anywhere as standalone system (edge cases excluded of course). Transactional resources are either by nature integrated with 3rd party systems (eg Payments, Billing in Italy with eInvoicing) or by operational requirement (ERP, CRMs like Salesforce,...). For that purpose I see meta data as a senseful extension on admin site for all transactional ressources (also payments, stock movements (even if we won't use them) and RMAs. Given that more and more countries switch to eInvoicing (Germany is next and US has had testing phases for B2B in 2022) in the coming years I personally (and I might well be alone with that opinion) deem meta data on orders a hard requirement to future proof the system.

### Customer Meta Data 
Customer meta data allows users to customize a cart (incomplete order) with either administrative (PO numbers,...) or customisation information (eg an URL to a picture to customize a shirt, text strings for incisions or in our case IMEIs to relate to a subscription) allowing to significantly extend the features without changing the underlying model. Fields should be accessible on front-end and backend. 

## Schema 
Meta Data should net a reliable outcome: 
"key1" : "value1" should be as applicable as "key2" : "value2", without restriction other than the quantity of storable key value pairs and limitations of the dimension of the value given that json as a format does not pose limits we should do that server side. I think it's a front-end job to render the information correctly for the public. 

## Implementation
Make a decent suggestion and we will deliver it, I think it's important to provide a logic to enable and disable this feature.  There can be different approaches: 
 - we stash a jsonb as suggested by jared in an additional column
 - A system wide polymorphic solution with an independent table that belongs to many records, with a boolean column for public/private and a helper method in there to validate on call.

### Nature of the Values
The system should be agnostic to the value contained. A decision has been made to store the data in additional columns in a jsonb which by now is relatively widely supported. Some preexisting installations might have to upgrade DBs (I am looking at SQLite).

"key1" : "value1" should lead to the same behaviour as "key2" : "value2" without requiring modification inside the code. Reasonable provisions should be taken inside the code base to edit the quantities and content size of key value pairs and appropriate errors should be returned where rate or size limits are exceeded. 

## Administrative Meta Data
Allow appropriate roles to customize resources with private fields not end-user accessible. 
R/W = Read and Write Access
|               | Admin   | Use Case                                                                                                                                  |
|---------------|---------|-------------------------------------------------------------------------------------------------------------------------------------------|
| **Order**     | **R/W** | **Add 3rd party system reference fields such as PO-Order or Dropshipping reference**                                                      |
| **Line Item** | **R/W** | **Add information to customize object such as link to an image for customization of a product or relate to a 3rd party system reference** |
| **RMA**       | **R/W** | **Add 3rd party system reference fields such as PO-Order or Dropshipping reference**                                                      |
| **Payment**   | **R/W** | **Add 3rd party system reference fields such as PO-Order or Dropshipping reference**                                                      |
| **Order**     | **R/W** | **Add 3rd party system reference fields such as PO-Order or Dropshipping reference**                                                      |
| Shipment      | R/W     | Add 3rd party system reference fields such as a delivery note                                                                             |
| Payment       | R/W     | Add 3rd party system reference fields for payment conciliation                                                                            |

## Customer Meta Data 

Allowing users to customize an incomplete order (or I'd say a cart) and call the information after a completed order. Admins should in an ideal case be allowed to edit those information after purchase, but I feel that can wait if technical limitations are currently in place. 

|               | User    | Admin   |    Use Case                                                                                                                                       |
|---------------|---------|---------|-------------------------------------------------------------------------------------------------------------------------------------------|
| **Order**     | **R/W** | **R/W** | **Add 3rd party system reference fields such as PO-Order,**                                                                               |
| **Line Item** | **R/W** | **R/W** | **Add information to customize object such as link to an image for customization of a product or relate to a 3rd party system reference** |
| User          | R/W     | R/W     | Add additional User Fields or References                                                                                                  |

### (Public) Catalogue Meta Data
Data that allows to extend the product catalogue to comply with legal requirements or marketing requirements well aware that surely different use cases will be hacked into it by others in the future. Given that the name Public Meta Data has been sufficiently burned I called it Catalogue Meta Data. 

## Example 1: Create order
```
{
  "order": {
    "email": "pinko.pallino@example.com",
    "customer_order_meta": [{
      "phone":"1234567890123456",
      "contract":"ref_123456"
      }],
    "line_items_attributes": [
      {
        "quantity": 1,
        "variant_id": 33,
        "customer_line_item_meta": [{
          "imei":"1234567890123456"
          }],   
      }]
    }
  }
```

## Example Reponse 1: Create order
```
{
  "additional_tax_total": "string",
  "adjustment_total": "string",
  "adjustments": [
    {
      "adjustable_id": 0,
      "adjustable_type": "string",
      "amount": "string",
      "created_at": "string",
      "display_amount": "string",
      "finalized": true,
      "id": 0,
      "label": "string",
      "source_id": 0,
      "source_type": "string",
      "updated_at": "string"
    }
  ],
  "bill_address": {
    "address1": "string",
    "address2": "string",
    "alternative_phone": "string",
    "city": "string",
    "company": "string",
    "country": {
      "id": 0,
      "iso": "string",
      "iso3": "string",
      "iso_name": "string",
      "name": "string",
      "numcode": 0
    },
    "country_id": 0,
    "country_iso": "string",
    "id": 0,
    "name": "string",
    "phone": "string",
    "state": {
      "abbr": "string",
      "country_id": 0,
      "id": 0,
      "name": "string"
    },
    "state_id": 0,
    "state_name": "string",
    "state_text": "string",
    "zipcode": "string"
  },
  "canceler_id": 0,
  "channel": "string",
  "checkout_steps": [
    "string"
  ],
  "completed_at": "string",
  "covered_by_store_credit": true,
  "created_at": "string",
  "credit_cards": [
    {
      "address": null,
      "cc_type": "string",
      "id": 0,
      "last_digits": "string",
      "month": "string",
      "name": "string",
      "year": "string"
    }
  ],
    {
      "adjustments": [
        {
          "adjustable_id": 0,
          "adjustable_type": "string",
          "amount": "string",
          "created_at": "string",
          "display_amount": "string",
          "finalized": true,
          "id": 0,
          "label": "string",
          "source_id": 0,
          "source_type": "string",
          "updated_at": "string"
        }
      ],
      "display_amount": "string",
      "id": 0,
      "price": "string",
      "quantity": 0,
      "single_display_amount": "string",
      "total": "string",
      "variant": {
        "cost_price": "string",
        "depth": "string",
        "description": "string",
        "display_price": "string",
        "height": "string",
        "id": 0,
        "images": [
          {
            "alt": "string",
            "attachment_content_type": "string",
            "attachment_file_name": "string",
            "attachment_height": 0,
            "attachment_updated_at": "string",
            "attachment_width": 0,
            "id": 0,
            "large_url": "string",
            "mini_url": "string",
            "position": 0,
            "product_url": "string",
            "small_url": "string",
            "type": "string",
            "viewable_id": 0,
            "viewable_type": "string"
          }
        ],
        "in_stock": true,
        "is_backorderable": true,
        "is_destroyed": true,
        "is_master": true,
        "name": "string",
        "option_values": [
          {
            "id": 0,
            "name": "string",
            "option_type_id": 0,
            "option_type_name": "string",
            "option_type_presentation": "string",
            "presentation": "string"
          }
        ],
        "options_text": "string",
        "price": "string",
        "sku": "string",
        "slug": "string",
        "total_on_hand": 0,
        "track_inventory": true,
        "weight": "string",
        "width": "string"
      },
      "variant_id": 0,
      "customer_line_item_meta": [{
        "imei":"1234567890123456"
        }],
    }
  ],
  "number": "string",
  "order_total_after_store_credit": "string",
  "payment_methods": [
    {
      "id": 0,
      "method_type": "string",
      "name": "string",
      "partial_name": "string"
    }
  ],
  "payment_state": "string",
  "payment_total": "string",
  "payments": [
    {
      "amount": "string",
      "avs_response": "string",
      "created_at": "string",
      "display_amount": "string",
      "id": 0,
      "payment_method": {
        "id": 0,
        "method_type": "string",
        "name": "string",
        "partial_name": "string"
      },
      "payment_method_id": 0,
      "source": {
        "cc_type": "string",
        "gateway_customer_profile_id": "string",
        "gateway_payment_profile_id": "string",
        "id": 0,
        "last_digits": "string",
        "month": "string",
        "name": "string",
        "year": "string"
      },
      "source_id": 0,
      "source_type": 0,
      "state": "string",
      "updated_at": "string"
    }
  ],
  "permissions": {
    "can_update": true
  },
  "ship_address": {
    "address1": "string",
    "address2": "string",
    "alternative_phone": "string",
    "city": "string",
    "company": "string",
    "country": {
      "id": 0,
      "iso": "string",
      "iso3": "string",
      "iso_name": "string",
      "name": "string",
      "numcode": 0
    },
    "country_id": 0,
    "country_iso": "string",
    "id": 0,
    "name": "string",
    "phone": "string",
    "state": {
      "abbr": "string",
      "country_id": 0,
      "id": 0,
      "name": "string"
    },
    "state_id": 0,
    "state_name": "string",
    "state_text": "string",
    "zipcode": "string"
  },
  "ship_total": "string",
  "shipment_state": "string",
  "shipments": [
    {
      "adjustments": [
        {
          "adjustable_id": 0,
          "adjustable_type": "string",
          "amount": "string",
          "created_at": "string",
          "display_amount": "string",
          "finalized": true,
          "id": 0,
          "label": "string",
          "source_id": 0,
          "source_type": "string",
          "updated_at": "string"
        }
      ],
      "cost": "string",
      "id": 0,
      "manifest": [
        [
          {
            "quantity": 0,
            "states": {
              "on_hand": 0
            },
            "variant_id": 0
          }
        ]
      ],
      "number": "string",
      "order_id": "string",
      "customer_order_meta": [{
          "phone":"1234567890123456",
          "contract":"ref_123456"
          }],
      "selected_shipping_rate": {
        "cost": "string",
        "display_cost": "string",
        "id": 0,
        "name": "string",
        "selected": true,
        "shipping_method_code": "string",
        "shipping_method_id": 0
      },
      "shipped_at": "string",
      "shipping_methods": [
        {
          "code": "string",
          "id": 0,
          "name": "string",
          "shipping_categories": [
            {
              "id": 0,
              "name": "string"
            }
          ],
          "zones": [
            {
              "description": "string",
              "id": 0,
              "name": "string"
            }
          ]
        }
      ],
      "shipping_rates": [
        {
          "cost": "string",
          "display_cost": "string",
          "id": 0,
          "name": "string",
          "selected": true,
          "shipping_method_code": "string",
          "shipping_method_id": 0
        }
      ],
      "state": "string",
      "stock_location_name": "string",
      "tracking": "string",
      "tracking_url": "string"
    }
  ],
  "special_instructions": "string",
  "state": "string",
  "tax_total": "string",
  "token": "string",
  "total": "string",
  "total_applicable_store_credit": "string",
  "total_quantity": 0,
  "updated_at": "string",
  "user_id": 0
}
```

# Original Post
**Introduction**
Currently custom fields need to be hardcoded into the solution. 
There are endless needs to customize orders, for example: 
- some countries require particular fields for the invoice (Italy requires an electronic invoice ID for every billing address)
- some products might have customization features such as: Incissions, custom text on the product, ...
- Orders might need additional addresses on file

Spree found an elegant and easy to implement approach by creating a metadata storrage inside the primary objects.
[Metadata on Spree Commerce](https://github.com/spree/spree/commit/f4903648b091504020def4a176bcdff29a4f6048)
We would sponsor or merge this feature upon guidance from the core team.

**Desired behavior**
Custom values can be added to an order from front-end using a meta data field in major ressources.

### PR DESCRIPTION
**Pull request by fthobe**
Closes #5897
Concerns #5951

# Breaking Changes
This feature breaks sqlite versions predating to [December 2023](https://sqlite.org/jsonb.html), verify your requirements before migrating. 

# Introduction 

## Overview
This PR introduces the concept of metadata fields to solidus. The purpose of metadata fields is to allow customers and admins alike to provide additional information to transactions to either extend the informations contained or allow to insert additional data to correlate transactions with third party systems. 

Examples for data can be: 

- any transaction itself such as orders, RMAs, payments and stock movements;
- individual items contained inside an order (line items);
- match users with 3rd party systems.

Possible Applications on a very high level are:

- customers that want to add Purchase Order information to an order; 
- administrators that want to add a ticket number to an RMA.

The current scope of meta data are following ressources:  
- Users
- Orders
- Customer Returns and any from of correlated transactions
- Payments
- Shipments
- Line Items

## How is the additional information stored?
for each of the above resources two columns have been created:
- customer_metadata
- admin_metadata

The resources store the information as jsonb.

## What is the access model?
Cancancan has been used to allow users to write data with the current scope just extended by the additional fields:
- Users can create / delete / alter metadata on orders only till the payment itself is processed,
- Admins have universal access R/W access to metadata at all stages of transactions.

## Testing
Extensive test cases have been added. 

# Detailed Overview 

### Overview 
Meta data can be broken down in three large topics visible in the table below:

|                         | Use Case                                                                                                                                                              |
|-------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Administrative Metadata | Information required to correlate all transactions to 3rd party systems.                                                                                              |
| Customer Metadata       | Information allowing customers to customize orders (eg options to store information like a text string or link to an image) or correlate transactions (such as POs).  |

### Administrative Metadata
Transactional resources are either by nature integrated with 3rd party systems (eg Payments, Billing in Italy with eInvoicing) or by operational requirement (ERP, CRMs like Salesforce,...). Meta data as an extension on admin site for all transactional resources to connect the transactional resources to any of such systems. Given that more and more countries will switch to a form of eInvoicing in the coming years meta data allows to fetch or store additional information in those transactions.

### Customer Meta Data 
Customer meta data allows users to customize a cart with either administrative (PO numbers,...) or customisation information (eg an URL to a picture to customize a shirt, text strings for incisions or in our case IMEIs to relate to a subscription) allowing to significantly extend the features without changing the underlying model. Fields should be accessible on front-end and backend. 

## Schema 
Meta Data should net a reliable outcome: 
"key1" : "value1" should be as applicable as "key2" : "value2", without restriction other than the quantity of storable key value pairs and limitations of the dimension of the value given that json as a format does not pose limits we should do that server side. 

Future models to reserve or block certain key names might be possible. 

### Nature of the Values
The system is agnostic to the value contained. A decision has been made to store the data in additional columns in a jsonb which by now is relatively widely supported. Some preexisting installations might have to upgrade DBs, older sqlite versions dating before Jan 2024 are therefor not supported and need to be updated.

"key1" : "value1" should lead to the same behaviour as "key2" : "value2" without requiring modification inside the code. Reasonable provisions should be taken inside the code base to edit the quantities and content size of key value pairs and appropriate errors should be returned where rate or size limits are exceeded. 

## Administrative Meta Data
Allow appropriate roles to customize resources with private fields not end-user accessible. 
R/W = Read and Write Access
|               | Admin   | Use Case                                                                                                                                  |
|---------------|---------|-------------------------------------------------------------------------------------------------------------------------------------------|
| **Order**     | **R/W** | **Add 3rd party system reference fields such as PO-Order or Dropshipping reference**                                                      |
| **Line Item** | **R/W** | **Add information to customize object such as link to an image for customization of a product or relate to a 3rd party system reference** |
| **RMA**       | **R/W** | **Add 3rd party system reference fields such as PO-Order or Dropshipping reference**                                                      |
| **Payment**   | **R/W** | **Add 3rd party system reference fields such as PO-Order or Dropshipping reference**                                                      |
| **Order**     | **R/W** | **Add 3rd party system reference fields such as PO-Order or Dropshipping reference**                                                      |
| Shipment      | R/W     | Add 3rd party system reference fields such as a delivery note                                                                             |
| Payment       | R/W     | Add 3rd party system reference fields for payment conciliation                                                                            |
| User       | R/W     | Add a 3rd party reference |

## Customer Meta Data 

Allowing users to customize an incomplete order (or I'd say a cart) and call the information after a completed order. Admins should in an ideal case be allowed to edit those information after purchase, but I feel that can wait if technical limitations are currently in place. 

|               | User    | Admin   |    Use Case                                                                                                                                       |
|---------------|---------|---------|-------------------------------------------------------------------------------------------------------------------------------------------|
| **Order**     | **R/W** | **R/W** | **Add 3rd party system reference fields such as PO-Order,**                                                                               |
| **Line Item** | **R/W** | **R/W** | **Add information to customize object such as link to an image for customization of a product or relate to a 3rd party system reference** |
| User          | R/W     | R/W     | Add additional User Fields or References                                                                                                  |

### CODE REVIEW

File: core/spec/lib/spree/app_configuration_spec.rb [hunk 1]
```diff
@@ -222,4 +222,22 @@ class DummyClass; end;
     expect(prefs.admin_vat_location.state_id).to eq(nil)
     expect(prefs.admin_vat_location.country_id).to eq(nil)
   end
+
+  describe '@max_keys' do
```
Comment (tvdeyen) [inline core/spec/lib/spree/app_configuration_spec.rb:226]: describe meta_data_max_keys

File: core/spec/lib/spree/app_configuration_spec.rb [hunk 2]
```diff
@@ -222,4 +222,22 @@ class DummyClass; end;
...
+    it 'is 6 by default' do
+      expect(prefs[:meta_data_max_keys]).to eq(6)
+    end
+  end
+
+  describe '@max_key_length' do
```
Comment (tvdeyen) [inline core/spec/lib/spree/app_configuration_spec.rb:232]: etc. pp. wrong describe

File: core/spec/lib/spree/app_configuration_spec.rb [hunk 3]
```diff
@@ -222,4 +222,22 @@ class DummyClass; end;
...
+    it 'is 16 by default' do
+      expect(prefs[:meta_data_max_key_length]).to eq(16)
+    end
+  end
+
+  describe '@max_value_length' do
```
Comment (tvdeyen) [inline core/spec/lib/spree/app_configuration_spec.rb:238]: etc. pp. wrong describe

File: core/app/models/concerns/spree/metadata.rb [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+      attribute :customer_metadata, :json, default: {}
+      attribute :admin_metadata, :json, default: {}
+
+      validate :validate_metadata_limits
+    end
+
+    private
+
+    def validate_metadata_limits
+      %i[customer_metadata admin_metadata].each { |column| validate_metadata_column(column) }
```
Comment (tvdeyen) [inline core/app/models/concerns/spree/metadata.rb:21]: can we make this a class method inside this module for better customisability?

```rb
def self.meta_data_columns = %i[customer_metadata admin_metadata]
```

that way stores can decide which meta data type they support and extend it pretty easily

File: core/app/models/concerns/spree/metadata.rb [hunk 5]
```diff
@@ -0,0 +1,54 @@
...
+      errors.add(column, "key '#{key}' exceeds #{max_key_length} characters")
+    end
+
+    def validate_metadata_value(key, value, column, max_value_length)
+      return unless value.to_s.length > max_value_length
+
+      errors.add(column, "value for key '#{key}' exceeds #{max_value_length} characters")
+    end
+  end
+end
```
Comment (tvdeyen) [inline core/app/models/concerns/spree/metadata.rb:58]: I also would like to have tests in this commit. Ideally a [shared rspec example](https://rspec.info/features/3-12/rspec-core/example-groups/shared-examples/)

so that we can add those shared examples into the models this module is mixed in and verify the API still works

File: core/app/models/spree/customer_return.rb [hunk 6]
```diff
@@ -2,6 +2,8 @@
 
 module Spree
   class CustomerReturn < Spree::Base
+    include Metadata
+
```
Comment (tvdeyen) [inline core/app/models/spree/customer_return.rb:6]: This commit lacks tests. Ideally we would use shared examples for meta data inside of the existing models specs.

File: api/lib/spree/api_configuration.rb [hunk 7]
```diff
@@ -14,7 +14,7 @@ class ApiConfiguration < Preferences::Configuration
 
     preference :variant_attributes, :array, default: [
       :id, :name, :sku, :weight, :height, :width, :depth, :is_master,
-      :slug, :description, :track_inventory
+      :slug, :description, :track_inventory, :customer_metadata
```
Comment (tvdeyen) [inline api/lib/spree/api_configuration.rb]: this commit also lacks integration specs (ideally via rspec request specs)

File: api/app/controllers/spree/api/orders_controller.rb [hunk 8]
```diff
@@ -112,12 +112,19 @@ def mine
...
           {}
         end
       end
 
+      def prevent_customer_metadata_update
+        return unless @order&.completed? && cannot?(:admin, Spree::Order)
+
+        params[:order].delete(:customer_metadata) if params[:order]
+      end
+
```
Comment (tvdeyen) [inline api/app/controllers/spree/api/orders_controller.rb:127]: this commit needs specs to verify its integrity

File: api/app/controllers/spree/api/base_controller.rb [hunk 9]
```diff
@@ -18,6 +18,9 @@ class BaseController < ActionController::Base
       class_attribute :admin_line_item_attributes
       self.admin_line_item_attributes = [:price, :variant_id, :sku]
 
+      class_attribute :admin_metadata_attributes
+      self.admin_metadata_attributes = [{ admin_metadata: {} }]
+
```
Comment (tvdeyen) [inline api/app/controllers/spree/api/base_controller.rb:23]: this change also needs specs to verify its integrity

File: api/spec/requests/spree/api/customer_returns_spec.rb [hunk 10]
```diff
@@ -59,6 +59,14 @@ module Spree::Api
         expect(json_response).to have_attributes(attributes)
       end
 
+      it "can view admin_metadata" do
```
Comment (tvdeyen) [inline api/spec/requests/spree/api/customer_returns_spec.rb:62]: can you please split up this commit and add it to the commits that introduces the changes? I commented on the individual commits (hopefully github will display this correctly, if not please go through this pr commit by commit in order to see the comments)

File: core/lib/spree/app_configuration.rb [hunk 11]
```diff
@@ -209,6 +209,14 @@ class AppConfiguration < Preferences::Configuration
...
     preference :orders_per_page, :integer, default: 15
 
+    # @!attribute [rw] meta_data_validation_enabled
+    #   @return [Boolean] Indicates whether validation for customer and admin metadata columns is enabled.
+    #   When this is set to true, the following preferences will be used to validate the metadata:
+    #   - The maximum number of keys that can be added to the metadata columns (meta_data_max_keys).
+    #   - The maximum length of each key in the metadata columns (meta_data_max_key_length).
+    #   - The maximum length of each value in the metadata columns (meta_data_max_value_length).
+    #   (default: +true+)
+    preference :meta_data_validation_enabled, :boolean, default: false
```
Comment (tvdeyen) [inline core/lib/spree/app_configuration.rb:219]: I like the idea of one toggle. 👍🏻

File: core/spec/models/spree/order_spec.rb [hunk 12]
```diff
@@ -2161,43 +2161,79 @@ def validate(line_item)
 
     %w[customer_metadata admin_metadata].each do |metadata_type|
       describe metadata_type.to_s do
-        it "does not allow more than 6 keys" do
-          subject.send("#{metadata_type}=", invalid_metadata_keys)
+        context "when metadata validation is enabled" do
```
Comment (tvdeyen) [inline core/spec/models/spree/order_spec.rb:2164]: this commit is great, because it introduces the change together with a test and a descriptive commit message 👍🏻 it would be great if the previous commits also would be like this.

**Comment by fthobe** [comment]
@shahmayur001 it was discussed with Thomas to squash everything at the end.

**Comment by tvdeyen** [comment]
> @shahmayur001 it was discussed with Thomas to squash everything at the end.

To be fully transparent I offered to squash merge this if @shahmayur001 is not able to rewrite the git history to our standards.

File: core/spec/lib/spree/app_configuration_spec.rb (hunk 1 above)
Comment (shahmayur001) [reply core/spec/lib/spree/app_configuration_spec.rb]: Resolved!

File: core/spec/lib/spree/app_configuration_spec.rb (hunk 2 above)
Comment (shahmayur001) [reply core/spec/lib/spree/app_configuration_spec.rb]: Resolved!

File: core/spec/lib/spree/app_configuration_spec.rb (hunk 3 above)
Comment (shahmayur001) [reply core/spec/lib/spree/app_configuration_spec.rb]: Resolved!

File: core/app/models/concerns/spree/metadata.rb (hunk 4 above)
Comment (shahmayur001) [reply core/app/models/concerns/spree/metadata.rb]: Resolved!

File: core/app/models/concerns/spree/metadata.rb (hunk 5 above)
Comment (shahmayur001) [reply core/app/models/concerns/spree/metadata.rb:64]: Created a shared spec, Resolved!

File: core/app/models/spree/customer_return.rb (hunk 6 above)
Comment (shahmayur001) [reply core/app/models/spree/customer_return.rb:6]: Resolved!

File: api/lib/spree/api_configuration.rb (hunk 7 above)
Comment (shahmayur001) [reply api/lib/spree/api_configuration.rb]: Resolved!

File: api/app/controllers/spree/api/orders_controller.rb (hunk 8 above)
Comment (shahmayur001) [reply api/app/controllers/spree/api/orders_controller.rb:127]: Resolved!

File: api/app/controllers/spree/api/base_controller.rb (hunk 9 above)
Comment (shahmayur001) [reply api/app/controllers/spree/api/base_controller.rb:23]: Updated commits with proper changes, Resolved!

File: api/spec/requests/spree/api/customer_returns_spec.rb (hunk 10 above)
Comment (shahmayur001) [reply api/spec/requests/spree/api/customer_returns_spec.rb:62]: Corrected commits with the respective changes, Resolved.

**Comment by fthobe** [comment]
@tvdeyen this should be all, all comments are resolved, the failed tests are either related to 

- flaky interfaces 
- https://github.com/solidusio/solidus/pull/6128

And are outside of the impact zone of this PR.

**Comment by shahmayur001** [comment]
@kennyadsl @tvdeyen Thank you so much for your guidance and support in helping us become more familiar with the Solidus community. As you know, we are completely new contributors, and we’ve likely made quite a few mistakes but we truly appreciate your patience. We’re actively learning from your feedback, taking notes, and doing our best to avoid repeating the same mistakes in the future. Your patience and insights are truly appreciated!

File: core/app/models/concerns/spree/metadata.rb (hunk 5 above)
Comment (tvdeyen) [reply core/app/models/concerns/spree/metadata.rb:64]: Nice. Thanks

**Review by tvdeyen — APPROVED** [review]
Thank you for your patience and the adjusting of your commits. This is very much appreciated
