### PR TITLE
Call empty only on incomplete orders

### LINKED ISSUE #4438: [API] empty cart endpoint raises 500 error with shipped order
**Solidus Version**:
all, including master

**How to reproduce**
Trying to `empty` a shipped order via API raises a 500 error, which is something we should try to avoid.

This can be easily demonstrated in the admin area:
* on the `Cart` tab, add an item to a new order, and keep this browser window as it is, we'll get back to it later;
* add the address, payment, and finalize the order in a different browser window/tab;
* ship the order;
* go back to the `Cart` browser window and click the `Empty Cart` button. Web developer tools will show a 500 error, and no message is presented to the user.

**Context**

This is the method definition from the [API orders controller](https://github.com/solidusio/solidus/blob/master/api/app/controllers/spree/api/orders_controller.rb):
```ruby
      def empty
        authorize! :update, @order, order_token
        @order.empty!
        render plain: nil, status: 204
      end
```

`@order.empty!` [tries to reset the cart](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/order.rb#L450) by destroying the associated records, but shipped shipments [cannot be destroyed](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/shipment.rb#L340). The error bubbles up to the controller, where it's not handled. 
Screen Shot 2022-06-22 at 11 18 08 AM

### PR DESCRIPTION
**Pull request by nvandoorn**
## Summary

Fixes #4438. This change is based on #5418 from @nirnaeth.

There are two notable changes from #5418:

1. Call order.incomplete? instead of order.shipped? as suggested by @kennyadsl
2. Updated the new feature spec to make it pass.

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [x] I have written a thorough PR description.
- [x] I have kept my commits small and atomic.
- [x] [I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

The following are not always needed:

- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

### CODE REVIEW

**Comment by nvandoorn** [comment]
Looks like we have a few spec failures that we're currently addressing.

File: backend/spec/features/admin/orders/order_details_spec.rb [hunk 1]
```diff
@@ -399,6 +399,31 @@
...
+                  address: order.ship_address,
+                  shipping_method: shipment.shipping_method
+                )
+
+                accept_alert 'Are you sure you want to delete this record?' do
+                  click_on 'Empty Cart'
+                end
+
+                expect(page.current_path).to eq(spree.cart_admin_order_path(order))
+                expect(page).not_to have_content(order.line_items.first.variant.sku)
```
Comment (tvdeyen) [inline backend/spec/features/admin/orders/order_details_spec.rb:424]: This can lead to false positives. Can we expect an empty order message instead?

```suggestion
                expect(page).to have_content I18n.t('spree.your_order_is_empty_add_product')
```

Comment (nvandoorn) [reply backend/spec/features/admin/orders/order_details_spec.rb]: Thanks @tvdeyen. I ended up re-writting most of this spec in the latest revision, so let me know what you think :)

**Review by jarednorman — APPROVED** [review]

**Review by MadelineCollier — APPROVED** [review]
