### PR TITLE
Skip forgery protection in api controllers

### LINKED ISSUE #2799: API endpoints produces InvalidAuthenticityToken with POST
### Steps to reproduce
``curl -X POST -k -H 'X-Spree-Token: 1111111111111111111111111111111' -i 'https://example.com/api/orders'``

I get ``"ActionController::InvalidAuthenticityToken in Spree::Api::OrdersController#create"
in actionpack (5.2.0) lib/action_controller/metal/request_forgery_protection.rb:211:in `handle_unverified_request'``

### Expected behavior
The API endpoints should not require an authenticity_token.

In Spree, the CSRF protection is disabled for JSON/XML requests:
``protect_from_forgery unless: -> { request.format.json? || request.format.xml? }`` (https://github.com/spree/spree/blob/master/api/app/controllers/spree/api/base_controller.rb)

this is missing in https://github.com/solidusio/solidus/blob/master/api/app/controllers/spree/api/base_controller.rb

Maybe I am missing something, but I did not found a way to get the API to work correctly.

### System configuration
**Solidus Version**: 2.6.0

**Extensions in use**: none

### PR DESCRIPTION
**Pull request by kennyadsl**
Fixes #2799

Rails is now enabling forgery protection by default so we need to explicitly disable it for api requests, as described here:

http://api.rubyonrails.org/classes/ActionController/RequestForgeryProtection.html

This PR also enables forgery protection by default in the specs dummy app so that we can really test that the api code is working in a real Rails 5.2+ environment.

### CODE REVIEW

File: core/lib/spree/testing_support/dummy_app.rb [hunk 1]
```diff
@@ -12,9 +12,16 @@
 
 require 'solidus_core'
 
+# @private
+def forgery_protected_by_default?
+  Gem::Version.new(Rails.version) >= Gem::Version.new('5.2')
```
Comment (BenMorganIO) [inline core/lib/spree/testing_support/dummy_app.rb]: Is this still needed with the latest master?

Comment (BenMorganIO) [reply core/lib/spree/testing_support/dummy_app.rb]: Yep, still needed: https://github.com/solidusio/solidus/blob/master/core/solidus_core.gemspec#L27
