### PR TITLE
Validate presence of product on a Variant

### LINKED ISSUE #2011: Variant validation allows no product associated
### Steps to reproduce
Just follow [this](https://asciinema.org/a/ck2bktzpcdpapoij6h0ztasr1) asciinema

### Expected behavior
Variants must **always** have an associated product to be valid

### Actual behavior
If I set `variant.product` as `nil` doing `variant.save` the validation doesn't fail.
So variants can be product orphan.

### System configuration
Solidus master branch

### PR DESCRIPTION
**Pull request by jhawthorn**
It might also make sense to add a DB constraint.

Fixes #2011

### CODE REVIEW

File: core/app/models/spree/variant.rb [hunk 1]
```diff
@@ -61,6 +61,7 @@ class Variant < Spree::Base
 
     validate :check_price
 
+    validates :product, presence: true
```
Comment (tvdeyen) [inline core/app/models/spree/variant.rb]: Can't we instead use `optional: false` on the `belongs_to :product` above?
