### PR TITLE
set_position conflicts with acts_as_list

### LINKED ISSUE #5508: Spree::Variant#set_position conflicts with acts_as_list
When creating a Variant, acts_as_list and set_position callback increment position.  
So I think [this commit](https://github.com/spree/spree/commit/08f159b8ecc6f999e7337539798ff45a1b9e89b6) needs to be picked.

**Solidus Version**:
4.3.0.dev

**To Reproduce**

```
$ RAILS_ENV=test bin/rails c
irb(main):001> require 'factory_bot_rails'
irb(main):002> variant = FactoryBot.create :variant
...
irb(main):003> variant.product.master.position
=> 1
irb(main):004> variant.position
=> 3
irb(main):005> multi_variant = FactoryBot.create :variant, product: variant.product
...
irb(main):006> multi_variant.position
=> 5
```

**Current behavior**
Not increase by 1

**Expected behavior**
Increase by 1

### PR DESCRIPTION
**Pull request by tkimi**
## Summary

Fixes #5508

Remove set_position callback

I thought about changing the test as in this diff, but decided to just remove it since this is just testing acts_as_list.

```diff
diff --git a/core/spec/models/spree/variant_spec.rb b/core/spec/models/spree/variant_spec.rb
index 84cab17c1f..7246a74e60 100644
--- a/core/spec/models/spree/variant_spec.rb
+++ b/core/spec/models/spree/variant_spec.rb
@@ -574,11 +574,13 @@ RSpec.describe Spree::Variant, type: :model do
     end
   end
 
-  # Regression test for https://github.com/spree/spree/issues/2744
-  describe "set_position" do
-    it "sets variant position after creation" do
-      variant = create(:variant)
-      expect(variant.position).to_not be_nil
+  describe "acts_as_list" do
+    it "sets variant position by acts_as_list" do
+      expect(variant.product.master.position).to eq 1
+      expect(variant.position).to eq 2
+
+      multi_variant = create(:variant, product: variant.product)
+      expect(multi_variant.position).to eq 3
     end
   end
 ```
## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [x] I have written a thorough PR description.
- [x] I have kept my commits small and atomic.
- [x] [I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

The following are not always needed:

- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

### CODE REVIEW

File: core/spec/models/spree/variant_spec.rb [hunk 1]
```diff
@@ -574,14 +574,6 @@
...
   end
 
-  # Regression test for https://github.com/spree/spree/issues/2744
-  describe "set_position" do
-    it "sets variant position after creation" do
-      variant = create(:variant)
-      expect(variant.position).to_not be_nil
-    end
-  end
-
```
Comment (jarednorman) [inline core/spec/models/spree/variant_spec.rb:584]: Do we really want to remove this test? We still want to persist this behaviour, even if we're removing the callback, right?

**Review by jarednorman — CHANGES_REQUESTED** [review]

File: core/spec/models/spree/variant_spec.rb (hunk 1 above)
Comment (tkimi) [reply core/spec/models/spree/variant_spec.rb]: I wonder if I should write a test for "acts as list" only for Variant, but we feel safer with a spec.
So I added the test! 77aceb0

**Review by jarednorman — APPROVED** [review]
