### PR TITLE
Fix property destroy - use destroy instead of discard

### LINKED ISSUE #5576: [Admin] Undefined destroy method call on non soft deletable Spree::Property
Deletion of properties will fail with `undefined method discard_all`

**Solidus Version**: 4.3.0

**To Reproduce**
1. Go to Solidus Admin
2. Click on Products -> Properties
3. Select all items or try with a single one
4. Try to delete them with the Delete button - the app will fail

**Current behavior**
The application fails to delete Property records with `undefined method discard_all`

**Expected behavior**
Properties should be deleted with a success message popup.

**Screenshots**
Screenshot 2023-12-29 at 17 17 09

**Desktop (please complete the following information):**
 - OS: OS X Sonma 14.1 (23B74)
 - Browser: Chrome

**Additional context**
Rails version: 7.1.2
Ruby version: 3.2.2

Test failure:
Screenshot 2023-12-29 at 17 44 11

### PR DESCRIPTION
**Pull request by tonxyx**
As the `Spree::Property` object is not discardable, use the default `destroy_all` method

Fixes #5576

### CODE REVIEW

File: admin/spec/features/properties.rb [hunk 1]
```diff
@@ -6,19 +6,19 @@
   before { sign_in create(:admin_user, email: 'admin@example.com') }
 
   it "lists properties and allows deleting them" do
-    create(:property, name: "Type", presentation: "Type")
+    create(:property, name: "Type prop", presentation: "Type prop")
```
Comment (tonxyx) [inline admin/spec/features/properties.rb:9]: Changed "Type" to "Type prop" because of text Option types" used for the menu item which test recognizes as non deleted.

**Review by jarednorman — APPROVED** [review]

**Review by kennyadsl — APPROVED** [review]
Thanks for the contribution!

**Comment by kennyadsl** [comment]
@elia @rainerdema  I think we need to backport this to 4.3, adding the appropriate label.

**Review by elia — APPROVED** [review]

**Comment by elia** [comment]
@kennyadsl I just realized the PR is for solidus admin only, meaning that we don't need the back port since we can release independently.
