### PR TITLE
Use create_if_necessary instead of a simple find_or_initialize

### LINKED ISSUE #3467: Inconsistent Order Lookup Between Controllers
Hey folks,

I am looking for some insight here, perhaps you can help me. We ran into a case in production where an order shows up in the cart but upon trying to proceed with checkout, no order is found and the user is redirected back to the cart. 

This is fundamentally because in `Spree::OrdersController#edit`:
https://github.com/solidusio/solidus/blob/master/frontend/app/controllers/spree/orders_controller.rb#L42

```
@order = current_order || Spree::Order.incomplete.find_or_initialize_by(guest_token: cookies.signed[:guest_token])
```

However, in `Spree::CheckoutController#load_order`: 
https://github.com/solidusio/solidus/blob/master/frontend/app/controllers/spree/checkout_controller.rb#L136
``
@order = current_order
``

If we unpack `current_order` behavior further, you will see it uses a different query to load:
https://github.com/solidusio/solidus/blob/master/core/lib/spree/core/controller_helpers/order.rb#L86

```
order = Spree::Order.incomplete.lock(options[:lock]).find_by(current_order_params)
```

and

```
        def current_order_params
          { currency: current_pricing_options.currency, guest_token: cookies.signed[:guest_token], store_id: current_store.id, user_id: try_spree_current_user.try(:id) }
        end
```

In our specific case, the miss was happening because we had a state with the Order have a non-nil `user_id` and the query kept asking for `nil` because the other session did not exist. 

**Solidus Version**:
`master`

**To Reproduce**
I do not have all of the specific to reproduce but am hoping for some insightful discussion.

**Current behavior**
Orders and Checkout controllers load orders differently. 

**Expected behavior**
I would expect them to abide by the same business logic and am curious why that's not the case. I understand this behavior is inherited from a much older Spree release, but hoping folks have extra insight. 

Thanks, y'all!

### PR DESCRIPTION
**Pull request by elia**
**Description**

Using current_order with create_if_necessary creates order that are
much more complete adding info about the ip, creator and other meta
data that is better to have rather than not. Not to mention that it's
also more readable.

Fixes #3467

I did a historical check and no specific reason for doing it this way came about.
- https://github.com/solidusio/solidus/commit/3516aa39c903faeca1d18746bfeefc7b138b1cae
- https://github.com/solidusio/solidus/commit/4efa7898003f30ad265eba8a39e2f59dc3f5f24b

**Checklist:**
- [x] I have followed [Pull Request guidelines](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#pull-request-guidelines)
- [x] I have added a detailed description into each commit message
- [x] I have updated Guides and README accordingly to this change (if needed)
- [x] I have added tests to cover this change (if needed)
- [x] I have attached screenshots to this PR for visual changes (if needed)

### CODE REVIEW

**Comment by kennyadsl** [comment]
Please also read https://github.com/solidusio/solidus/issues/3467.

**Comment by kennyadsl** [comment]
Anyway, I was trying to make something similar and the only reason why I don't like this change is that we are writing something into the database on a GET request, which is not ideal (and could be an easy endpoint to target for DoS attacks).

I think another valid way to handle this would be redirecting the user to the `root_path` if they are trying to see the cart without a `current_order` in place. Or maybe the empty cart is something that customers want to see anyway?

**Comment by elia** [comment]
I think it's legitimate to have an empty cart page, and I actually saw it on many stores, usually with links to a product-list or with inline suggestions.

If we don't want to create an order upon visiting `/cart` it it's missing we I would suggest to let `current_order` learn how to initialize one. For example by accepting a `build_if_necessary` argument.

File: core/spec/lib/spree/core/controller_helpers/order_spec.rb [hunk 1]
```diff
@@ -74,6 +75,23 @@ class FakesController < ApplicationController
         }.from(nil).to("0.0.0.0")
       end
     end
+
+    context 'build_order_if_necessary option is true' do
+      subject { controller.current_order(build_order_if_necessary: true) }
+
+      it 'creates new order' do
```
Comment (spaghetticode) [inline core/spec/lib/spree/core/controller_helpers/order_spec.rb]: since the order is not persisted, IMO this should read `it builds a new order` instead.

File: core/spec/lib/spree/core/controller_helpers/order_spec.rb [hunk 2]
```diff
@@ -2,12 +2,13 @@
...
-  include Spree::Core::ControllerHelpers::Order
-end
-
 RSpec.describe Spree::Core::ControllerHelpers::Order, type: :controller do
-  controller(FakesController) {}
+  controller(ApplicationController) {
+    include Spree::Core::ControllerHelpers::Store
+    include Spree::Core::ControllerHelpers::Pricing
+    include Spree::Core::ControllerHelpers::Auth
+    include Spree::Core::ControllerHelpers::Order
```
Comment (spaghetticode) [inline core/spec/lib/spree/core/controller_helpers/order_spec.rb]: It's not evident to me why we need to include all these modules now, can you explain the reason?

Comment (elia) [reply core/spec/lib/spree/core/controller_helpers/order_spec.rb]: Previously there was the FakesController class that was shared among all controller helpers spec files. During the file loading (but before the specs were ran) each helper was including itself into that class. So, at the time the specs were ready to run, the FakesController class had all the helpers included. 

Now, instead, should be more clear on which helpers each helper depends, e.g. the `Order` helper needs methods from `Store`, `Pricing`, and `Auth`.

File: frontend/app/controllers/spree/orders_controller.rb [hunk 3]
```diff
@@ -39,7 +39,7 @@ def update
 
     # Shows the current incomplete order from the session
     def edit
-      @order = current_order || Spree::Order.incomplete.find_or_initialize_by(guest_token: cookies.signed[:guest_token])
+      @order = current_order(build_order_if_necessary: true)
       authorize! :read, @order, cookies.signed[:guest_token]
       associate_user
```
Comment (bitberryru) [inline frontend/app/controllers/spree/orders_controller.rb]: Great work, thank you!
Coincidentally, I also researched current_order behaviour and found some interesting points in legacy code.
1. Remove reduntant `find_or_initialize_by` and just build order (you fixed it, great!)
2. Remove `associate_user` call in OrdersController#edit

That code was added in this commit https://github.com/spree/spree/commit/a3d1f9acdbd5f0ec6c5eceb07116e30cd953948b

In that version when you call `current_order(true)` you create new order without any attributes (without current user, without store_id, without currency, without guest_token and so on, check it https://github.com/spree/spree/blob/a3d1f9acdbd5f0ec6c5eceb07116e30cd953948b/core/lib/spree/core/current_order.rb#L27). The logic of order creation was divided - in one place you create empty order, at another place you set necessary attributes such as user_id via `associate_user` call. This mistake is still here for 8 years despite the fact that in current version necessary attributes are set at `current_order`.

This method call can be safely removed.

P.S. `associate_user` defined at this concern `Spree::Core::ControllerHelpers::Order` and called only at two places - this one (reduntant) and before any action at `Spree::CheckoutController`. Perhaps it is also unnecessary, I will investigate)

Comment (elia) [reply frontend/app/controllers/spree/orders_controller.rb]: @bitberryru thanks for the analysis and the hint!

So basically, if we inline `associate_user` inside `spree/orders#edit` we get this:

```rb
    # Shows the current incomplete order from the session
    def edit
      @order = current_order(build_order_if_necessary: true)
      authorize! :read, @order, cookies.signed[:guest_token]

      # vvv Inlined version of #associate_user 
      if try_spree_current_user && (@order.user.blank? || @order.email.blank?)
        @order.associate_user!(try_spree_current_user)
      end

      if params[:id] && @order.number != params[:id]
        flash[:error] = t('spree.cannot_edit_orders')
        redirect_to cart_path
      end
    end
```

The idea is that it's the responsibility of the authentication system to do the association in case the order was created before the login, and we can safely assume that we'll never encounter a persisted order that is authorized (via guest_token) and not already associated to the current user.

Here's the solidus_auth_devise warden callback:

```rb
# Merges users orders to their account after sign in and sign up.
Warden::Manager.after_set_user except: :fetch do |user, auth, _opts|
  if auth.cookies.signed[:guest_token].present?
    if user.is_a?(Spree::User)
      Spree::Order.incomplete.where(guest_token: auth.cookies.signed[:guest_token], user_id: nil).each do |order|
        order.associate_user!(user)
      end
    end
  end
end
```

---

About the checkout controller seems like the code is executed in a different sequence:

```rb
  class CheckoutController < Spree::StoreController
    before_action :load_order                   # <<<< calls #current_order
    around_action :lock_order

    before_action :ensure_order_is_not_skipping_states
    before_action :ensure_order_not_completed
    before_action :ensure_checkout_allowed
    before_action :ensure_sufficient_stock_lines
    before_action :ensure_valid_state

    before_action :associate_user               # <<<< calls #associate_user
    before_action :check_authorization          # <<<< checks against the guest_token
    before_action :apply_coupon_code
```

I'd like to more research to be sure not to break something for some store… 

@kennyadsl @bitberryru what about dealing with removing `#associate_user` in another PR?

Comment (kennyadsl) [reply frontend/app/controllers/spree/orders_controller.rb]: Sure, another PR is perfect for this change.

Comment (kennyadsl) [reply frontend/app/controllers/spree/orders_controller.rb]: Moved the discussion in a separate issue: https://github.com/solidusio/solidus/issues/3559
