### PR TITLE
Fix permissions to see admin menu items

### LINKED ISSUE #3834: Settings menu is visible in admin login screen before logging in
After a fresh install, the settings menu is visible in the admin login screen. Clicking on any of its items just redirects back to the login screen.

**Solidus Version**: 2.11.1

**To Reproduce**
* Clone the solidus repo (master branch commit 304da6d1a72da1c2014bf809480e0c455ddbefe1)
* Create a new sandbox app following the steps in the readme. 
* Go to localhost:3000/admin/login
* Notice that the settings menu is visible in the sidebar to the left

**Current behavior**

The settings menu is visible when the admin user is not logged in.

**Expected behavior**

The settings menu should not be visible when the admin user is not logged in.

**Screenshots**

Screenshot 2020-11-08 at 20 00 42

### PR DESCRIPTION
**Pull request by kennyadsl**
**Description**

Closes #3834.

Right now a user without roles like logged users or guests user can see the admin menu partially, see https://github.com/solidusio/solidus/issues/3834. 

This behavior has been introduced with https://github.com/solidusio/solidus/commit/295df5e8d92e85b3c5a7fc6c761c32b691b81b75#diff-757abc24f29994c5e06e233c60ca1f3972c2f5019fba628df718eea681adb61fR68 and it happens because a non-admin user actually has permission to show zones and shipping methods; the current code is checking against the `:show` ability, so it seems to be legit.

We use `:admin` for the rest of the menu items checks though, and this is also what we use in the controller to determine if
we can access that page, see: https://github.com/solidusio/solidus/blob/3c8ffcc34f9248b286a9d4ca94d1f9a3197ac7b2/backend/app/controllers/spree/admin/base_controller.rb#L29

Test setup lines have been removed since they are useless now.

**Checklist:**
- [x] I have followed [Pull Request guidelines](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#pull-request-guidelines)
- [x] I have added a detailed description into each commit message
- [ ] I have updated Guides and README accordingly to this change (if needed)
- [ ] I have added tests to cover this change (if needed)
- [ ] I have attached screenshots to this PR for visual changes (if needed)

### CODE REVIEW

**Review by peterberkenbosch — APPROVED** [review]
👍 nice!

File: backend/spec/features/admin/homepage_spec.rb [hunk 1]
```diff
@@ -73,8 +73,6 @@
     custom_authorization! do |_user|
       can [:admin, :home], :dashboards
       can [:admin, :edit, :index, :show], Spree::Order
-      cannot [:show], Spree::StockLocation
-      cannot [:show], Spree::Zone
```
Comment (elia) [inline backend/spec/features/admin/homepage_spec.rb:77]: Shouldn't these two be changed to:

```rb
      cannot [:admin], Spree::StockLocation
      cannot [:admin], Spree::Zone
```

So we can be sure that the settings tab is still visible even when the user is not able to access some of its sub-resources?

**Review by elia — CHANGES_REQUESTED** [review]

**Review by jarednorman — APPROVED** [review]

File: backend/spec/features/admin/homepage_spec.rb (hunk 1 above)
Comment (kennyadsl) [reply backend/spec/features/admin/homepage_spec.rb:77]: Even with the suggested change, the settings tab is not visible. I could change it this way to make sure the settings tab is displayed if one of the inner tab can be accessed but this won't test that the rest of the settings are excluded:

```ruby
context 'as fakedispatch user' do
    before do
      allow_any_instance_of(Spree::Admin::BaseController).to receive(:try_spree_current_user).and_return(nil)
    end

    custom_authorization! do |_user|
      can [:admin, :home], :dashboards
      can [:admin, :edit, :index, :show], Spree::Order
      can [:admin], Spree::Zone
    end

    it 'should only display tabs fakedispatch has access to' do
      visit spree.admin_path
      expect(page).to have_link('Orders')
      expect(page).not_to have_link('Products')
      expect(page).not_to have_link('Promotions')
      expect(page).to have_link('Settings')
    end
  end
```

Let me think about something to test that.

Comment (kennyadsl) [reply backend/spec/features/admin/homepage_spec.rb:77]: @elia maybe I've got a possible test, let me know your thoughts!

Comment (elia) [reply backend/spec/features/admin/homepage_spec.rb:77]: Thanks @kennyadsl this look like a nice canary to catch if anything is going wrong with permissions without checking all the possible combinations 👍

**Review by elia — APPROVED** [review]

**Review by spaghetticode — APPROVED** [review]
