### PR TITLE
Filter unpriced products in taxon_preview

### LINKED ISSUE #2602: Product with no master price in currency of user crashes "offers" with NoMethodError in Spree::Taxons#show
### Steps to reproduce

1. Make taxons like Hardware -> SpecialHardware
2. Make a product with just USD master price of $1
3. Assign only taxon "SpecialHardware" to this product
4. As an EUR customer, go to http://localhost:3000/t/hardware (the parent taxon!)

### Expected behavior

Expect to see no products.

### Actual behavior

Shop crashes with `NoMethodError in Spree::Taxons#show`

```
Showing /var/lib/gems/2.3.0/gems/solidus_frontend-2.5.0.beta2/app/views/spree/shared/_products.html.erb where line #35 raised:

undefined method `to_d' for nil:NilClass
```

The line is:
`<span class="price selling" itemprop="price" content="<%= product.price_for(current_pricing_options).to_d %>">`

The crash occurs because `product.price_for(current_pricing_options)` is `nil` in that moment.

### System configuration
**Solidus Version**:
```
gem 'solidus', '2.5.0.beta2'
gem 'deface'
gem 'solidus_auth_devise', '2.1.0'
```

**Extensions in use**:
`gem 'solidus_paypal_braintree', github: 'solidusio/solidus_paypal_braintree', branch: :master
`

### PR DESCRIPTION
**Pull request by jhawthorn**
Previously, `taxon_preview` would return products without prices, resulting in an error.

This commit makes it respect the `current_pricing_options` and filter products which are available in the current price.

Fixes #2602

### CODE REVIEW

**Comment by jhawthorn** [comment]
Spec failure unrelated and should be fixed by #2607

File: frontend/spec/features/taxons_spec.rb [hunk 1]
```diff
@@ -134,4 +134,25 @@
...
+  # Regression test for https://github.com/solidusio/solidus/issues/2602
+  context "root taxon page" do
+    it "shows taxon previews" do
+      visit spree.nested_taxons_path(taxonomy.root)
+
+      expect(page).to have_css('ul.product-listing li', count: 2)
+      expect(page).to have_content("Superman T-Shirt", count: 2)
+    end
+
+    context "with prices in other currncy" do
```
Comment (tvdeyen) [inline frontend/spec/features/taxons_spec.rb]: > ~~currncy~~

currency
